export type TestQuestion = {
  type: 'multiple-choice';
  question: string;
  options: string[];
  correctAnswer: string;
};

export const day1TestQuestions: TestQuestion[] = [
  // Is/Am/Are Questions (40 questions)
  {
    type: 'multiple-choice',
    question: 'I ___ a student.',
    options: ['am', 'is', 'are'],
    correctAnswer: 'am',
  },
  {
    type: 'multiple-choice',
    question: 'She ___ happy today.',
    options: ['am', 'is', 'are'],
    correctAnswer: 'is',
  },
  {
    type: 'multiple-choice',
    question: 'They ___ my friends.',
    options: ['am', 'is', 'are'],
    correctAnswer: 'are',
  },
  {
    type: 'multiple-choice',
    question: 'You ___ learning English.',
    options: ['am', 'is', 'are'],
    correctAnswer: 'are',
  },
  {
    type: 'multiple-choice',
    question: 'It ___ a beautiful day.',
    options: ['am', 'is', 'are'],
    correctAnswer: 'is',
  },
  {
    type: 'multiple-choice',
    question: 'We ___ at school.',
    options: ['am', 'is', 'are'],
    correctAnswer: 'are',
  },
  {
    type: 'multiple-choice',
    question: 'He ___ my brother.',
    options: ['am', 'is', 'are'],
    correctAnswer: 'is',
  },
  {
    type: 'multiple-choice',
    question: 'I ___ ready to go.',
    options: ['am', 'is', 'are'],
    correctAnswer: 'am',
  },
  {
    type: 'multiple-choice',
    question: 'The cat ___ sleeping.',
    options: ['am', 'is', 'are'],
    correctAnswer: 'is',
  },
  {
    type: 'multiple-choice',
    question: 'You and I ___ good friends.',
    options: ['am', 'is', 'are'],
    correctAnswer: 'are',
  },
  {
    type: 'multiple-choice',
    question: 'The book ___ on the table.',
    options: ['am', 'is', 'are'],
    correctAnswer: 'is',
  },
  {
    type: 'multiple-choice',
    question: 'My parents ___ at home.',
    options: ['am', 'is', 'are'],
    correctAnswer: 'are',
  },
  {
    type: 'multiple-choice',
    question: 'I ___ very tired.',
    options: ['am', 'is', 'are'],
    correctAnswer: 'am',
  },
  {
    type: 'multiple-choice',
    question: 'The dog ___ barking.',
    options: ['am', 'is', 'are'],
    correctAnswer: 'is',
  },
  {
    type: 'multiple-choice',
    question: 'We ___ happy to help.',
    options: ['am', 'is', 'are'],
    correctAnswer: 'are',
  },
  {
    type: 'multiple-choice',
    question: 'She ___ a teacher.',
    options: ['am', 'is', 'are'],
    correctAnswer: 'is',
  },
  {
    type: 'multiple-choice',
    question: 'They ___ playing outside.',
    options: ['am', 'is', 'are'],
    correctAnswer: 'are',
  },
  {
    type: 'multiple-choice',
    question: 'I ___ from India.',
    options: ['am', 'is', 'are'],
    correctAnswer: 'am',
  },
  {
    type: 'multiple-choice',
    question: 'The flowers ___ beautiful.',
    options: ['am', 'is', 'are'],
    correctAnswer: 'are',
  },
  {
    type: 'multiple-choice',
    question: 'He ___ very smart.',
    options: ['am', 'is', 'are'],
    correctAnswer: 'is',
  },
  {
    type: 'multiple-choice',
    question: 'You ___ my best friend.',
    options: ['am', 'is', 'are'],
    correctAnswer: 'are',
  },
  {
    type: 'multiple-choice',
    question: 'I ___ excited about the trip.',
    options: ['am', 'is', 'are'],
    correctAnswer: 'am',
  },
  {
    type: 'multiple-choice',
    question: 'The children ___ in the park.',
    options: ['am', 'is', 'are'],
    correctAnswer: 'are',
  },
  {
    type: 'multiple-choice',
    question: 'She ___ reading a book.',
    options: ['am', 'is', 'are'],
    correctAnswer: 'is',
  },
  {
    type: 'multiple-choice',
    question: 'We ___ going to the market.',
    options: ['am', 'is', 'are'],
    correctAnswer: 'are',
  },
  {
    type: 'multiple-choice',
    question: 'It ___ raining outside.',
    options: ['am', 'is', 'are'],
    correctAnswer: 'is',
  },
  {
    type: 'multiple-choice',
    question: 'I ___ hungry.',
    options: ['am', 'is', 'are'],
    correctAnswer: 'am',
  },
  {
    type: 'multiple-choice',
    question: 'The students ___ studying.',
    options: ['am', 'is', 'are'],
    correctAnswer: 'are',
  },
  {
    type: 'multiple-choice',
    question: 'He ___ a doctor.',
    options: ['am', 'is', 'are'],
    correctAnswer: 'is',
  },
  {
    type: 'multiple-choice',
    question: 'You ___ very kind.',
    options: ['am', 'is', 'are'],
    correctAnswer: 'are',
  },
  {
    type: 'multiple-choice',
    question: 'I ___ learning English.',
    options: ['am', 'is', 'are'],
    correctAnswer: 'am',
  },
  {
    type: 'multiple-choice',
    question: 'The birds ___ singing.',
    options: ['am', 'is', 'are'],
    correctAnswer: 'are',
  },
  {
    type: 'multiple-choice',
    question: 'She ___ my sister.',
    options: ['am', 'is', 'are'],
    correctAnswer: 'is',
  },
  {
    type: 'multiple-choice',
    question: 'We ___ ready for the test.',
    options: ['am', 'is', 'are'],
    correctAnswer: 'are',
  },
  {
    type: 'multiple-choice',
    question: 'It ___ very hot today.',
    options: ['am', 'is', 'are'],
    correctAnswer: 'is',
  },
  {
    type: 'multiple-choice',
    question: 'I ___ happy to see you.',
    options: ['am', 'is', 'are'],
    correctAnswer: 'am',
  },
  {
    type: 'multiple-choice',
    question: 'The teachers ___ in the classroom.',
    options: ['am', 'is', 'are'],
    correctAnswer: 'are',
  },
  {
    type: 'multiple-choice',
    question: 'He ___ playing football.',
    options: ['am', 'is', 'are'],
    correctAnswer: 'is',
  },
  {
    type: 'multiple-choice',
    question: 'You ___ a good person.',
    options: ['am', 'is', 'are'],
    correctAnswer: 'are',
  },
  {
    type: 'multiple-choice',
    question: 'I ___ working hard.',
    options: ['am', 'is', 'are'],
    correctAnswer: 'am',
  },

  // A/An/The Questions (40 questions)
  {
    type: 'multiple-choice',
    question: 'I have ___ book.',
    options: ['a', 'an', 'the'],
    correctAnswer: 'a',
  },
  {
    type: 'multiple-choice',
    question: 'She has ___ apple.',
    options: ['a', 'an', 'the'],
    correctAnswer: 'an',
  },
  {
    type: 'multiple-choice',
    question: '___ book is on the table.',
    options: ['A', 'An', 'The'],
    correctAnswer: 'The',
  },
  {
    type: 'multiple-choice',
    question: 'He is ___ engineer.',
    options: ['a', 'an', 'the'],
    correctAnswer: 'an',
  },
  {
    type: 'multiple-choice',
    question: 'I saw ___ cat. ___ cat was small.',
    options: ['a, The', 'an, The', 'the, A'],
    correctAnswer: 'a, The',
  },
  {
    type: 'multiple-choice',
    question: 'This is ___ interesting book.',
    options: ['a', 'an', 'the'],
    correctAnswer: 'an',
  },
  {
    type: 'multiple-choice',
    question: 'I need ___ pen to write.',
    options: ['a', 'an', 'the'],
    correctAnswer: 'a',
  },
  {
    type: 'multiple-choice',
    question: 'She wants ___ orange.',
    options: ['a', 'an', 'the'],
    correctAnswer: 'an',
  },
  {
    type: 'multiple-choice',
    question: '___ sun is shining.',
    options: ['A', 'An', 'The'],
    correctAnswer: 'The',
  },
  {
    type: 'multiple-choice',
    question: 'He bought ___ umbrella.',
    options: ['a', 'an', 'the'],
    correctAnswer: 'an',
  },
  {
    type: 'multiple-choice',
    question: 'I have ___ dog.',
    options: ['a', 'an', 'the'],
    correctAnswer: 'a',
  },
  {
    type: 'multiple-choice',
    question: 'She is ___ honest person.',
    options: ['a', 'an', 'the'],
    correctAnswer: 'an',
  },
  {
    type: 'multiple-choice',
    question: '___ moon is bright tonight.',
    options: ['A', 'An', 'The'],
    correctAnswer: 'The',
  },
  {
    type: 'multiple-choice',
    question: 'I want ___ ice cream.',
    options: ['a', 'an', 'the'],
    correctAnswer: 'an',
  },
  {
    type: 'multiple-choice',
    question: 'He has ___ car.',
    options: ['a', 'an', 'the'],
    correctAnswer: 'a',
  },
  {
    type: 'multiple-choice',
    question: 'She is ___ artist.',
    options: ['a', 'an', 'the'],
    correctAnswer: 'an',
  },
  {
    type: 'multiple-choice',
    question: '___ sky is blue.',
    options: ['A', 'An', 'The'],
    correctAnswer: 'The',
  },
  {
    type: 'multiple-choice',
    question: 'I need ___ hour to finish.',
    options: ['a', 'an', 'the'],
    correctAnswer: 'an',
  },
  {
    type: 'multiple-choice',
    question: 'He is ___ student.',
    options: ['a', 'an', 'the'],
    correctAnswer: 'a',
  },
  {
    type: 'multiple-choice',
    question: 'She has ___ elephant toy.',
    options: ['a', 'an', 'the'],
    correctAnswer: 'an',
  },
  {
    type: 'multiple-choice',
    question: '___ earth is round.',
    options: ['A', 'An', 'The'],
    correctAnswer: 'The',
  },
  {
    type: 'multiple-choice',
    question: 'I saw ___ owl in the tree.',
    options: ['a', 'an', 'the'],
    correctAnswer: 'an',
  },
  {
    type: 'multiple-choice',
    question: 'He has ___ bicycle.',
    options: ['a', 'an', 'the'],
    correctAnswer: 'a',
  },
  {
    type: 'multiple-choice',
    question: 'She is ___ excellent teacher.',
    options: ['a', 'an', 'the'],
    correctAnswer: 'an',
  },
  {
    type: 'multiple-choice',
    question: '___ water is cold.',
    options: ['A', 'An', 'The'],
    correctAnswer: 'The',
  },
  {
    type: 'multiple-choice',
    question: 'I need ___ uniform for school.',
    options: ['a', 'an', 'the'],
    correctAnswer: 'a',
  },
  {
    type: 'multiple-choice',
    question: 'He is ___ actor.',
    options: ['a', 'an', 'the'],
    correctAnswer: 'an',
  },
  {
    type: 'multiple-choice',
    question: '___ door is open.',
    options: ['A', 'An', 'The'],
    correctAnswer: 'The',
  },
  {
    type: 'multiple-choice',
    question: 'I want ___ egg for breakfast.',
    options: ['a', 'an', 'the'],
    correctAnswer: 'an',
  },
  {
    type: 'multiple-choice',
    question: 'She has ___ house.',
    options: ['a', 'an', 'the'],
    correctAnswer: 'a',
  },
  {
    type: 'multiple-choice',
    question: 'He is ___ intelligent boy.',
    options: ['a', 'an', 'the'],
    correctAnswer: 'an',
  },
  {
    type: 'multiple-choice',
    question: '___ window is closed.',
    options: ['A', 'An', 'The'],
    correctAnswer: 'The',
  },
  {
    type: 'multiple-choice',
    question: 'I saw ___ ant on the floor.',
    options: ['a', 'an', 'the'],
    correctAnswer: 'an',
  },
  {
    type: 'multiple-choice',
    question: 'He has ___ phone.',
    options: ['a', 'an', 'the'],
    correctAnswer: 'a',
  },
  {
    type: 'multiple-choice',
    question: 'She is ___ old woman.',
    options: ['a', 'an', 'the'],
    correctAnswer: 'an',
  },
  {
    type: 'multiple-choice',
    question: '___ computer is new.',
    options: ['A', 'An', 'The'],
    correctAnswer: 'The',
  },
  {
    type: 'multiple-choice',
    question: 'I need ___ eraser.',
    options: ['a', 'an', 'the'],
    correctAnswer: 'an',
  },
  {
    type: 'multiple-choice',
    question: 'He has ___ bag.',
    options: ['a', 'an', 'the'],
    correctAnswer: 'a',
  },
  {
    type: 'multiple-choice',
    question: 'She is ___ amazing singer.',
    options: ['a', 'an', 'the'],
    correctAnswer: 'an',
  },
  {
    type: 'multiple-choice',
    question: '___ chair is comfortable.',
    options: ['A', 'An', 'The'],
    correctAnswer: 'The',
  },

  // Vocabulary Questions (40 questions)
  {
    type: 'multiple-choice',
    question: 'What is the opposite of "hot"?',
    options: ['cold', 'warm', 'cool', 'heat'],
    correctAnswer: 'cold',
  },
  {
    type: 'multiple-choice',
    question: 'What is the opposite of "big"?',
    options: ['small', 'large', 'huge', 'tiny'],
    correctAnswer: 'small',
  },
  {
    type: 'multiple-choice',
    question: 'What is the opposite of "happy"?',
    options: ['sad', 'joy', 'glad', 'cheerful'],
    correctAnswer: 'sad',
  },
  {
    type: 'multiple-choice',
    question: 'What is the opposite of "fast"?',
    options: ['slow', 'quick', 'rapid', 'swift'],
    correctAnswer: 'slow',
  },
  {
    type: 'multiple-choice',
    question: 'What is the opposite of "good"?',
    options: ['bad', 'great', 'nice', 'fine'],
    correctAnswer: 'bad',
  },
  {
    type: 'multiple-choice',
    question: 'A place where you buy books is called a ___.',
    options: ['bookstore', 'library', 'school', 'office'],
    correctAnswer: 'bookstore',
  },
  {
    type: 'multiple-choice',
    question: 'A person who teaches is called a ___.',
    options: ['teacher', 'student', 'doctor', 'engineer'],
    correctAnswer: 'teacher',
  },
  {
    type: 'multiple-choice',
    question: 'A place where you see a doctor is called a ___.',
    options: ['hospital', 'school', 'market', 'park'],
    correctAnswer: 'hospital',
  },
  {
    type: 'multiple-choice',
    question: 'What do you use to write?',
    options: ['pen', 'book', 'table', 'chair'],
    correctAnswer: 'pen',
  },
  {
    type: 'multiple-choice',
    question: 'What do you wear on your feet?',
    options: ['shoes', 'hat', 'shirt', 'gloves'],
    correctAnswer: 'shoes',
  },
  {
    type: 'multiple-choice',
    question: 'What is the opposite of "old"?',
    options: ['young', 'new', 'ancient', 'aged'],
    correctAnswer: 'young',
  },
  {
    type: 'multiple-choice',
    question: 'What is the opposite of "day"?',
    options: ['night', 'morning', 'evening', 'afternoon'],
    correctAnswer: 'night',
  },
  {
    type: 'multiple-choice',
    question: 'What is the opposite of "up"?',
    options: ['down', 'high', 'top', 'above'],
    correctAnswer: 'down',
  },
  {
    type: 'multiple-choice',
    question: 'What is the opposite of "open"?',
    options: ['close', 'shut', 'locked', 'sealed'],
    correctAnswer: 'close',
  },
  {
    type: 'multiple-choice',
    question: 'What is the opposite of "clean"?',
    options: ['dirty', 'neat', 'tidy', 'pure'],
    correctAnswer: 'dirty',
  },
  {
    type: 'multiple-choice',
    question: 'A person who cooks food is called a ___.',
    options: ['cook', 'waiter', 'farmer', 'driver'],
    correctAnswer: 'cook',
  },
  {
    type: 'multiple-choice',
    question: 'A place where you buy food is called a ___.',
    options: ['market', 'hospital', 'school', 'library'],
    correctAnswer: 'market',
  },
  {
    type: 'multiple-choice',
    question: 'What do you use to cut paper?',
    options: ['scissors', 'pen', 'ruler', 'eraser'],
    correctAnswer: 'scissors',
  },
  {
    type: 'multiple-choice',
    question: 'What do you use to tell time?',
    options: ['clock', 'book', 'pen', 'bag'],
    correctAnswer: 'clock',
  },
  {
    type: 'multiple-choice',
    question: 'What do you drink when you are thirsty?',
    options: ['water', 'food', 'bread', 'rice'],
    correctAnswer: 'water',
  },
  {
    type: 'multiple-choice',
    question: 'What is the opposite of "strong"?',
    options: ['weak', 'powerful', 'mighty', 'tough'],
    correctAnswer: 'weak',
  },
  {
    type: 'multiple-choice',
    question: 'What is the opposite of "light"?',
    options: ['dark', 'bright', 'shiny', 'clear'],
    correctAnswer: 'dark',
  },
  {
    type: 'multiple-choice',
    question: 'What is the opposite of "rich"?',
    options: ['poor', 'wealthy', 'expensive', 'costly'],
    correctAnswer: 'poor',
  },
  {
    type: 'multiple-choice',
    question: 'What is the opposite of "easy"?',
    options: ['difficult', 'simple', 'hard', 'tough'],
    correctAnswer: 'difficult',
  },
  {
    type: 'multiple-choice',
    question: 'What is the opposite of "full"?',
    options: ['empty', 'complete', 'filled', 'packed'],
    correctAnswer: 'empty',
  },
  {
    type: 'multiple-choice',
    question: 'A person who drives a car is called a ___.',
    options: ['driver', 'teacher', 'doctor', 'cook'],
    correctAnswer: 'driver',
  },
  {
    type: 'multiple-choice',
    question: 'A place where children learn is called a ___.',
    options: ['school', 'hospital', 'market', 'park'],
    correctAnswer: 'school',
  },
  {
    type: 'multiple-choice',
    question: 'What do you use to open a door?',
    options: ['key', 'pen', 'book', 'bag'],
    correctAnswer: 'key',
  },
  {
    type: 'multiple-choice',
    question: 'What do you use to see in the dark?',
    options: ['light', 'book', 'pen', 'water'],
    correctAnswer: 'light',
  },
  {
    type: 'multiple-choice',
    question: 'What do you eat for breakfast?',
    options: ['bread', 'pen', 'book', 'chair'],
    correctAnswer: 'bread',
  },
  {
    type: 'multiple-choice',
    question: 'What is the opposite of "wet"?',
    options: ['dry', 'damp', 'moist', 'soaked'],
    correctAnswer: 'dry',
  },
  {
    type: 'multiple-choice',
    question: 'What is the opposite of "loud"?',
    options: ['quiet', 'noisy', 'sound', 'voice'],
    correctAnswer: 'quiet',
  },
  {
    type: 'multiple-choice',
    question: 'What is the opposite of "near"?',
    options: ['far', 'close', 'next', 'beside'],
    correctAnswer: 'far',
  },
  {
    type: 'multiple-choice',
    question: 'What is the opposite of "thick"?',
    options: ['thin', 'fat', 'wide', 'broad'],
    correctAnswer: 'thin',
  },
  {
    type: 'multiple-choice',
    question: 'What is the opposite of "long"?',
    options: ['short', 'tall', 'high', 'big'],
    correctAnswer: 'short',
  },
  {
    type: 'multiple-choice',
    question: 'A person who fixes cars is called a ___.',
    options: ['mechanic', 'teacher', 'doctor', 'cook'],
    correctAnswer: 'mechanic',
  },
  {
    type: 'multiple-choice',
    question: 'A place where you play is called a ___.',
    options: ['playground', 'hospital', 'office', 'library'],
    correctAnswer: 'playground',
  },
  {
    type: 'multiple-choice',
    question: 'What do you use to carry books?',
    options: ['bag', 'pen', 'water', 'food'],
    correctAnswer: 'bag',
  },
  {
    type: 'multiple-choice',
    question: 'What do you use to clean the floor?',
    options: ['broom', 'pen', 'book', 'chair'],
    correctAnswer: 'broom',
  },
  {
    type: 'multiple-choice',
    question: 'What do you sit on?',
    options: ['chair', 'pen', 'book', 'water'],
    correctAnswer: 'chair',
  },

  // Sentence Structure Questions (40 questions)
  {
    type: 'multiple-choice',
    question: 'Which sentence is correct?',
    options: ['I am going to school.', 'I going to school.', 'I goes to school.', 'I go to schools.'],
    correctAnswer: 'I am going to school.',
  },
  {
    type: 'multiple-choice',
    question: 'Which sentence is correct?',
    options: ['She is my friend.', 'She are my friend.', 'She am my friend.', 'She be my friend.'],
    correctAnswer: 'She is my friend.',
  },
  {
    type: 'multiple-choice',
    question: 'Which sentence is correct?',
    options: ['They are playing.', 'They is playing.', 'They am playing.', 'They be playing.'],
    correctAnswer: 'They are playing.',
  },
  {
    type: 'multiple-choice',
    question: 'Which sentence is correct?',
    options: ['He has a book.', 'He have a book.', 'He having a book.', 'He haves a book.'],
    correctAnswer: 'He has a book.',
  },
  {
    type: 'multiple-choice',
    question: 'Which sentence is correct?',
    options: ['We are students.', 'We is students.', 'We am students.', 'We be students.'],
    correctAnswer: 'We are students.',
  },
  {
    type: 'multiple-choice',
    question: 'Which sentence is correct?',
    options: ['I like apples.', 'I likes apples.', 'I liking apples.', 'I liked apples.'],
    correctAnswer: 'I like apples.',
  },
  {
    type: 'multiple-choice',
    question: 'Which sentence is correct?',
    options: ['She reads books.', 'She read books.', 'She reading books.', 'She readed books.'],
    correctAnswer: 'She reads books.',
  },
  {
    type: 'multiple-choice',
    question: 'Which sentence is correct?',
    options: ['They go to school.', 'They goes to school.', 'They going to school.', 'They goed to school.'],
    correctAnswer: 'They go to school.',
  },
  {
    type: 'multiple-choice',
    question: 'Which sentence is correct?',
    options: ['He is happy.', 'He are happy.', 'He am happy.', 'He be happy.'],
    correctAnswer: 'He is happy.',
  },
  {
    type: 'multiple-choice',
    question: 'Which sentence is correct?',
    options: ['You are kind.', 'You is kind.', 'You am kind.', 'You be kind.'],
    correctAnswer: 'You are kind.',
  },
  {
    type: 'multiple-choice',
    question: 'Which sentence is correct?',
    options: ['I have a pen.', 'I has a pen.', 'I having a pen.', 'I haves a pen.'],
    correctAnswer: 'I have a pen.',
  },
  {
    type: 'multiple-choice',
    question: 'Which sentence is correct?',
    options: ['She likes music.', 'She like music.', 'She liking music.', 'She liked music.'],
    correctAnswer: 'She likes music.',
  },
  {
    type: 'multiple-choice',
    question: 'Which sentence is correct?',
    options: ['They are happy.', 'They is happy.', 'They am happy.', 'They be happy.'],
    correctAnswer: 'They are happy.',
  },
  {
    type: 'multiple-choice',
    question: 'Which sentence is correct?',
    options: ['He plays football.', 'He play football.', 'He playing football.', 'He played football.'],
    correctAnswer: 'He plays football.',
  },
  {
    type: 'multiple-choice',
    question: 'Which sentence is correct?',
    options: ['We have books.', 'We has books.', 'We having books.', 'We haves books.'],
    correctAnswer: 'We have books.',
  },
  {
    type: 'multiple-choice',
    question: 'Which sentence is correct?',
    options: ['I am a teacher.', 'I is a teacher.', 'I are a teacher.', 'I be a teacher.'],
    correctAnswer: 'I am a teacher.',
  },
  {
    type: 'multiple-choice',
    question: 'Which sentence is correct?',
    options: ['She writes well.', 'She write well.', 'She writing well.', 'She writed well.'],
    correctAnswer: 'She writes well.',
  },
  {
    type: 'multiple-choice',
    question: 'Which sentence is correct?',
    options: ['They eat lunch.', 'They eats lunch.', 'They eating lunch.', 'They eated lunch.'],
    correctAnswer: 'They eat lunch.',
  },
  {
    type: 'multiple-choice',
    question: 'Which sentence is correct?',
    options: ['He is tall.', 'He are tall.', 'He am tall.', 'He be tall.'],
    correctAnswer: 'He is tall.',
  },
  {
    type: 'multiple-choice',
    question: 'Which sentence is correct?',
    options: ['You have a car.', 'You has a car.', 'You having a car.', 'You haves a car.'],
    correctAnswer: 'You have a car.',
  },
  {
    type: 'multiple-choice',
    question: 'Which sentence is correct?',
    options: ['I work hard.', 'I works hard.', 'I working hard.', 'I worked hard.'],
    correctAnswer: 'I work hard.',
  },
  {
    type: 'multiple-choice',
    question: 'Which sentence is correct?',
    options: ['She is beautiful.', 'She are beautiful.', 'She am beautiful.', 'She be beautiful.'],
    correctAnswer: 'She is beautiful.',
  },
  {
    type: 'multiple-choice',
    question: 'Which sentence is correct?',
    options: ['They study English.', 'They studies English.', 'They studying English.', 'They studied English.'],
    correctAnswer: 'They study English.',
  },
  {
    type: 'multiple-choice',
    question: 'Which sentence is correct?',
    options: ['He has a dog.', 'He have a dog.', 'He having a dog.', 'He haves a dog.'],
    correctAnswer: 'He has a dog.',
  },
  {
    type: 'multiple-choice',
    question: 'Which sentence is correct?',
    options: ['We are friends.', 'We is friends.', 'We am friends.', 'We be friends.'],
    correctAnswer: 'We are friends.',
  },
  {
    type: 'multiple-choice',
    question: 'Which sentence is correct?',
    options: ['I love my family.', 'I loves my family.', 'I loving my family.', 'I loved my family.'],
    correctAnswer: 'I love my family.',
  },
  {
    type: 'multiple-choice',
    question: 'Which sentence is correct?',
    options: ['She cooks food.', 'She cook food.', 'She cooking food.', 'She cooked food.'],
    correctAnswer: 'She cooks food.',
  },
  {
    type: 'multiple-choice',
    question: 'Which sentence is correct?',
    options: ['They are teachers.', 'They is teachers.', 'They am teachers.', 'They be teachers.'],
    correctAnswer: 'They are teachers.',
  },
  {
    type: 'multiple-choice',
    question: 'Which sentence is correct?',
    options: ['He runs fast.', 'He run fast.', 'He running fast.', 'He runned fast.'],
    correctAnswer: 'He runs fast.',
  },
  {
    type: 'multiple-choice',
    question: 'Which sentence is correct?',
    options: ['You are smart.', 'You is smart.', 'You am smart.', 'You be smart.'],
    correctAnswer: 'You are smart.',
  },
  {
    type: 'multiple-choice',
    question: 'Which sentence is correct?',
    options: ['I have a sister.', 'I has a sister.', 'I having a sister.', 'I haves a sister.'],
    correctAnswer: 'I have a sister.',
  },
  {
    type: 'multiple-choice',
    question: 'Which sentence is correct?',
    options: ['She speaks English.', 'She speak English.', 'She speaking English.', 'She speaked English.'],
    correctAnswer: 'She speaks English.',
  },
  {
    type: 'multiple-choice',
    question: 'Which sentence is correct?',
    options: ['They live here.', 'They lives here.', 'They living here.', 'They lived here.'],
    correctAnswer: 'They live here.',
  },
  {
    type: 'multiple-choice',
    question: 'Which sentence is correct?',
    options: ['He is strong.', 'He are strong.', 'He am strong.', 'He be strong.'],
    correctAnswer: 'He is strong.',
  },
  {
    type: 'multiple-choice',
    question: 'Which sentence is correct?',
    options: ['We play games.', 'We plays games.', 'We playing games.', 'We played games.'],
    correctAnswer: 'We play games.',
  },
  {
    type: 'multiple-choice',
    question: 'Which sentence is correct?',
    options: ['I am ready.', 'I is ready.', 'I are ready.', 'I be ready.'],
    correctAnswer: 'I am ready.',
  },
  {
    type: 'multiple-choice',
    question: 'Which sentence is correct?',
    options: ['She knows the answer.', 'She know the answer.', 'She knowing the answer.', 'She knowed the answer.'],
    correctAnswer: 'She knows the answer.',
  },
  {
    type: 'multiple-choice',
    question: 'Which sentence is correct?',
    options: ['They are busy.', 'They is busy.', 'They am busy.', 'They be busy.'],
    correctAnswer: 'They are busy.',
  },
  {
    type: 'multiple-choice',
    question: 'Which sentence is correct?',
    options: ['He wants water.', 'He want water.', 'He wanting water.', 'He wanted water.'],
    correctAnswer: 'He wants water.',
  },
  {
    type: 'multiple-choice',
    question: 'Which sentence is correct?',
    options: ['You have time.', 'You has time.', 'You having time.', 'You haves time.'],
    correctAnswer: 'You have time.',
  },

  // Reading Comprehension Questions (40 questions)
  {
    type: 'multiple-choice',
    question: 'What color is the cat in the story?',
    options: ['White and brown', 'Black and white', 'Orange', 'Gray'],
    correctAnswer: 'White and brown',
  },
  {
    type: 'multiple-choice',
    question: 'What does the cat drink every day?',
    options: ['Milk', 'Water', 'Juice', 'Tea'],
    correctAnswer: 'Milk',
  },
  {
    type: 'multiple-choice',
    question: 'Where does the cat sleep?',
    options: ['On a soft bed', 'On the floor', 'On a chair', 'Outside'],
    correctAnswer: 'On a soft bed',
  },
  {
    type: 'multiple-choice',
    question: 'How does the family feel about the cat?',
    options: ['They love the cat', 'They ignore the cat', 'They are afraid of the cat', 'They dislike the cat'],
    correctAnswer: 'They love the cat',
  },
  {
    type: 'multiple-choice',
    question: 'What is the cat\'s name in the story?',
    options: ['Not mentioned', 'Tom', 'Fluffy', 'Whiskers'],
    correctAnswer: 'Not mentioned',
  },
  {
    type: 'multiple-choice',
    question: 'The cat is described as:',
    options: ['Small', 'Big', 'Huge', 'Tiny'],
    correctAnswer: 'Small',
  },
  {
    type: 'multiple-choice',
    question: 'What does "soft bed" mean?',
    options: ['Comfortable place to sleep', 'Hard surface', 'Cold floor', 'Wooden chair'],
    correctAnswer: 'Comfortable place to sleep',
  },
  {
    type: 'multiple-choice',
    question: 'The story is about:',
    options: ['A pet cat', 'A wild cat', 'A dog', 'A bird'],
    correctAnswer: 'A pet cat',
  },
  {
    type: 'multiple-choice',
    question: 'What does the cat do every day?',
    options: ['Drinks milk', 'Goes outside', 'Plays with toys', 'Runs away'],
    correctAnswer: 'Drinks milk',
  },
  {
    type: 'multiple-choice',
    question: 'The word "love" in the story means:',
    options: ['Care deeply for', 'Hate', 'Ignore', 'Fear'],
    correctAnswer: 'Care deeply for',
  },
  {
    type: 'multiple-choice',
    question: 'How many colors does the cat have?',
    options: ['Two', 'One', 'Three', 'Four'],
    correctAnswer: 'Two',
  },
  {
    type: 'multiple-choice',
    question: 'The cat is a:',
    options: ['Pet', 'Wild animal', 'Farm animal', 'Zoo animal'],
    correctAnswer: 'Pet',
  },
  {
    type: 'multiple-choice',
    question: 'What does "every day" mean?',
    options: ['Daily', 'Sometimes', 'Never', 'Rarely'],
    correctAnswer: 'Daily',
  },
  {
    type: 'multiple-choice',
    question: 'The family\'s feeling toward the cat is:',
    options: ['Positive', 'Negative', 'Neutral', 'Angry'],
    correctAnswer: 'Positive',
  },
  {
    type: 'multiple-choice',
    question: 'Where is the cat\'s bed?',
    options: ['Not specified', 'In the garden', 'On the roof', 'In the street'],
    correctAnswer: 'Not specified',
  },
  {
    type: 'multiple-choice',
    question: 'The cat is described as having:',
    options: ['White and brown colors', 'Only white', 'Only brown', 'Black color'],
    correctAnswer: 'White and brown colors',
  },
  {
    type: 'multiple-choice',
    question: 'What type of text is this?',
    options: ['A story', 'A poem', 'A letter', 'A recipe'],
    correctAnswer: 'A story',
  },
  {
    type: 'multiple-choice',
    question: 'The main character is:',
    options: ['A cat', 'A dog', 'A person', 'A bird'],
    correctAnswer: 'A cat',
  },
  {
    type: 'multiple-choice',
    question: 'What does "small" mean?',
    options: ['Not big', 'Very large', 'Huge', 'Giant'],
    correctAnswer: 'Not big',
  },
  {
    type: 'multiple-choice',
    question: 'The story tells us the cat:',
    options: ['Lives with a family', 'Lives alone', 'Lives in the forest', 'Lives in a zoo'],
    correctAnswer: 'Lives with a family',
  },
  {
    type: 'multiple-choice',
    question: 'What is the tone of the story?',
    options: ['Warm and loving', 'Sad', 'Scary', 'Angry'],
    correctAnswer: 'Warm and loving',
  },
  {
    type: 'multiple-choice',
    question: 'The cat\'s bed is:',
    options: ['Soft', 'Hard', 'Cold', 'Wet'],
    correctAnswer: 'Soft',
  },
  {
    type: 'multiple-choice',
    question: 'What does the family do for the cat?',
    options: ['Love and care for it', 'Ignore it', 'Hurt it', 'Sell it'],
    correctAnswer: 'Love and care for it',
  },
  {
    type: 'multiple-choice',
    question: 'The story is written in:',
    options: ['Simple English', 'Complex English', 'Another language', 'Poetry form'],
    correctAnswer: 'Simple English',
  },
  {
    type: 'multiple-choice',
    question: 'What can we learn from the story?',
    options: ['Families can love pets', 'Cats are dangerous', 'Pets are bad', 'Animals are scary'],
    correctAnswer: 'Families can love pets',
  },
  {
    type: 'multiple-choice',
    question: 'The cat drinks milk:',
    options: ['Every day', 'Sometimes', 'Never', 'Once a week'],
    correctAnswer: 'Every day',
  },
  {
    type: 'multiple-choice',
    question: 'What is the setting of the story?',
    options: ['A home', 'A forest', 'A school', 'A hospital'],
    correctAnswer: 'A home',
  },
  {
    type: 'multiple-choice',
    question: 'The cat is:',
    options: ['A pet animal', 'A wild animal', 'A dangerous animal', 'A farm animal'],
    correctAnswer: 'A pet animal',
  },
  {
    type: 'multiple-choice',
    question: 'What does "white and brown" describe?',
    options: ['The cat\'s colors', 'The bed', 'The milk', 'The family'],
    correctAnswer: 'The cat\'s colors',
  },
  {
    type: 'multiple-choice',
    question: 'The story shows that:',
    options: ['Pets are loved', 'Pets are ignored', 'Pets are scary', 'Pets are bad'],
    correctAnswer: 'Pets are loved',
  },
  {
    type: 'multiple-choice',
    question: 'How many lines is the story?',
    options: ['Five', 'Three', 'Ten', 'Twenty'],
    correctAnswer: 'Five',
  },
  {
    type: 'multiple-choice',
    question: 'The cat sleeps on:',
    options: ['A bed', 'The floor', 'A tree', 'The roof'],
    correctAnswer: 'A bed',
  },
  {
    type: 'multiple-choice',
    question: 'What is the main idea?',
    options: ['A family loves their cat', 'Cats are dangerous', 'Milk is good', 'Beds are soft'],
    correctAnswer: 'A family loves their cat',
  },
  {
    type: 'multiple-choice',
    question: 'The word "family" means:',
    options: ['People living together', 'Animals', 'Friends', 'Strangers'],
    correctAnswer: 'People living together',
  },
  {
    type: 'multiple-choice',
    question: 'What does the cat need?',
    options: ['Milk and a bed', 'Only food', 'Only water', 'Nothing'],
    correctAnswer: 'Milk and a bed',
  },
  {
    type: 'multiple-choice',
    question: 'The story is:',
    options: ['About a pet', 'About a person', 'About a place', 'About food'],
    correctAnswer: 'About a pet',
  },
  {
    type: 'multiple-choice',
    question: 'What makes the cat happy?',
    options: ['Love and care', 'Being alone', 'Being hungry', 'Being cold'],
    correctAnswer: 'Love and care',
  },
  {
    type: 'multiple-choice',
    question: 'The cat is part of:',
    options: ['A family', 'A zoo', 'A farm', 'A forest'],
    correctAnswer: 'A family',
  },
  {
    type: 'multiple-choice',
    question: 'What does "soft" mean?',
    options: ['Not hard', 'Very hard', 'Cold', 'Hot'],
    correctAnswer: 'Not hard',
  },
  {
    type: 'multiple-choice',
    question: 'The story teaches us:',
    options: ['To care for pets', 'To ignore pets', 'To fear pets', 'To avoid pets'],
    correctAnswer: 'To care for pets',
  },
];
