/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Time = IDL.Int;
export const TestAttempt = IDL.Record({
  'completionTime' : Time,
  'user' : IDL.Principal,
  'score' : IDL.Nat,
});
export const InterviewAnalysis = IDL.Record({
  'question' : IDL.Text,
  'feedback' : IDL.Text,
  'answer' : IDL.Text,
  'timestamp' : Time,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addInterviewAnalysis' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearMyProgressReport' : IDL.Func([], [], []),
  'forceRefreshIndiaNews' : IDL.Func([], [IDL.Text], []),
  'forceRefreshNews' : IDL.Func([], [IDL.Text], []),
  'getAllCompletedDays' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCompletedDaysCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getCourseProgress' : IDL.Func(
      [IDL.Principal],
      [IDL.Nat, IDL.Nat],
      ['query'],
    ),
  'getDay1TestAttempts' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(TestAttempt)],
      ['query'],
    ),
  'getIndiaNews' : IDL.Func([], [IDL.Text], []),
  'getInterviewAnalysis' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(InterviewAnalysis)],
      ['query'],
    ),
  'getMyProgressReport' : IDL.Func([], [IDL.Vec(InterviewAnalysis)], ['query']),
  'getNews' : IDL.Func([], [IDL.Text], []),
  'getNextLockedDay' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
  'getUnlockedDaysCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserHighScore' : IDL.Func([IDL.Principal], [IDL.Opt(IDL.Nat)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'handleScore' : IDL.Func([IDL.Nat], [IDL.Text], []),
  'hasUserPassedTest' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isDayLocked' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
  'isDayUnlocked' : IDL.Func([IDL.Principal, IDL.Nat], [IDL.Bool], ['query']),
  'resetProgress' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'unlockDayForUser' : IDL.Func([IDL.Principal], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Time = IDL.Int;
  const TestAttempt = IDL.Record({
    'completionTime' : Time,
    'user' : IDL.Principal,
    'score' : IDL.Nat,
  });
  const InterviewAnalysis = IDL.Record({
    'question' : IDL.Text,
    'feedback' : IDL.Text,
    'answer' : IDL.Text,
    'timestamp' : Time,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addInterviewAnalysis' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearMyProgressReport' : IDL.Func([], [], []),
    'forceRefreshIndiaNews' : IDL.Func([], [IDL.Text], []),
    'forceRefreshNews' : IDL.Func([], [IDL.Text], []),
    'getAllCompletedDays' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCompletedDaysCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getCourseProgress' : IDL.Func(
        [IDL.Principal],
        [IDL.Nat, IDL.Nat],
        ['query'],
      ),
    'getDay1TestAttempts' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(TestAttempt)],
        ['query'],
      ),
    'getIndiaNews' : IDL.Func([], [IDL.Text], []),
    'getInterviewAnalysis' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(InterviewAnalysis)],
        ['query'],
      ),
    'getMyProgressReport' : IDL.Func(
        [],
        [IDL.Vec(InterviewAnalysis)],
        ['query'],
      ),
    'getNews' : IDL.Func([], [IDL.Text], []),
    'getNextLockedDay' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
    'getUnlockedDaysCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserHighScore' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(IDL.Nat)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'handleScore' : IDL.Func([IDL.Nat], [IDL.Text], []),
    'hasUserPassedTest' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isDayLocked' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
    'isDayUnlocked' : IDL.Func([IDL.Principal, IDL.Nat], [IDL.Bool], ['query']),
    'resetProgress' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'unlockDayForUser' : IDL.Func([IDL.Principal], [], []),
  });
};

export const init = ({ IDL }) => { return []; };